obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.30,-0.20 ], [-0.30, 0.20,], [0.30, 0.20], [0.30, -0.20]]

inflation_radius: 0.75
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: hokuyo, data_type: LaserScan, topic: scan, marking: true, clearing: true}